#!/bin/zsh
names=("pacman" "AUR" "mamba" )
typeset -A ups
ups[pacman]="sudo powerpill -Syu"
ups[AUR]="paru -Sayu"
ups[mamba]="micromamba update -n default -c conda-forge --all"

for name in $names; do
    prompt=$(echo "\033[0;36mPerform $name update? [Y/n] \033[0m")
    read -sk "?${prompt}"
    echo -n "\n" # More self documenting then echo "" for new line
    case "$REPLY" in
        [nN][oO]|[nN])
            echo "    Skipping."
            ;;
        *)
            eval $ups[$name]
            ;;
    esac
done

echo "Updates Complete."
